server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/enochdb
    username: postgres
    password: ouss
    driver-class-name: org.postgresql.Driver
  web:
    # Ceci dit à Spring de chercher les ressources statiques dans le dossier 'uploads'
    # 'file:./uploads/' fait référence au dossier uploads à la racine du projet Spring Boot
    resources:
      static-locations: "classpath:/static/,file:./uploads/"
      # Ceci indique à Spring de mapper le chemin de l'URL à votre dossier de fichiers.
  jpa:
    hibernate:
      ddl-auto: update   # pour repartir propre; ensuite passe à 'update'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: false            # on désactive Flyway pour le dev simple

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs
    disable-swagger-default-url: true

app:
  jwt:
    secret: "change-me-to-a-256-bit-secret-at-least-32-bytes-long-1234567890"
    expiration-minutes: 120
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG